#!/usr/bin/env python3
"""Assemble the EQS Música static pages from src/.

    python3 tools/build.py

Edit src/ (partials, sections) and assets/ (site.css, site.js), then run this.
The generated HTML files are committed so Vercel still deploys with no build step.
Never hand-edit the generated pages — the next build overwrites them.
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"

GENERATED_NOTE = "<!-- Generated by tools/build.py from src/ — edit src/, not this file. -->\n"

# Where each old single-page anchor now lives. Used for every href="#…" in partials and sections.
ROUTES = {
    "#top": "/",
    "#about": "/about/",
    "#services": "/about/#services",
    "#journal": "/about/#journal",
    "#roster": "/artists/",
    "#releases": "/artists/#releases",
    "#derekvinci": "/derekvinci/",
    "#newsletter": "/newsletter/",
    "#creators": "/creators/",
    "#new-artist": "/apply/",
    "#contact": "/booking/",
}

PAGES = [
    {
        "path": "/",
        "title": "EQS MÚSICA — #1 in Tropical Music | Record Label, Production &amp; Bookings",
        "og_title": "EQS MÚSICA — #1 in Tropical Music",
        "description": "EQS Música — #1 in tropical music. Record label, production, and bookings by DerekVinci. Orlando, Florida.",
        "sections": ["hero", "about", "stats", "@featured", "partners", "final-cta"],
    },
    {
        "path": "/artists/",
        "title": "Artists | EQS MÚSICA",
        "og_title": "EQS Música Artists",
        "description": "The EQS Música roster — J Salez, Tony Lozano, Vinny Rivera, Johandy, Jhonny Evidence, Lee Sanz, Albin St' Rose, and Angel Rico.",
        "sections": ["roster", "stats", "releases", "final-cta"],
    },
    {
        "path": "/about/",
        "title": "About | EQS MÚSICA",
        "og_title": "About EQS Música",
        "description": "Founded in Boston in 1998 by DerekVinci and based in Orlando since 2006 — EQS Música is a tropical and Latin music label, studio, and booking agency.",
        "sections": ["about-story", "services", "stats", "partners", "journal"],
    },
    {
        "path": "/derekvinci/",
        "title": "DerekVinci | EQS MÚSICA",
        "og_title": "DerekVinci — Founder of EQS Música",
        "description": "DerekVinci — audio engineer, producer, and founder of EQS Música since 1998.",
        "sections": ["derekvinci", "derek-productions", "final-cta"],
    },
    {
        "path": "/newsletter/",
        "title": "Newsletter | EQS MÚSICA",
        "og_title": "The EQS Brief",
        "description": "The EQS Brief — label news, releases, and tour dates from EQS Música.",
        "sections": ["newsletter"],
    },
    {
        "path": "/creators/",
        "title": "Creator Program | EQS MÚSICA",
        "og_title": "EQS Creator Program",
        "description": "Editors, videographers, photographers, and designers — submit your work to the EQS Creator Program.",
        "sections": ["creators"],
    },
    {
        "path": "/apply/",
        "title": "Artist Application | EQS MÚSICA",
        "og_title": "Apply to EQS Música",
        "description": "Apply to join EQS Música. We look for artists who are serious, consistent, and investing in their careers.",
        "sections": ["new-artist"],
    },
    {
        "path": "/booking/",
        "title": "Booking | EQS MÚSICA",
        "og_title": "Book an EQS Artist",
        "description": "Book EQS Música artists for festivals, private events, and international tours.",
        "sections": ["contact", "final-cta"],
    },
]


# Home only: links shared before the split (eqsmusica.com/#roster) jump straight to the new page,
# inline in <head> so the home page never flashes first.
LEGACY_REDIRECT = """  <script>
    (function () {
      var routes = %s;
      var target = routes[location.hash];
      if (target) location.replace(target);
    })();
  </script>
"""


def read(rel):
    return (SRC / rel).read_text(encoding="utf-8")


def reroute(html, page_path):
    """Point in-page anchors at their new pages; keep a bare hash when the target is this page."""

    def sub(match):
        href = match.group(1)
        target = ROUTES.get(href)
        if target is None:
            return match.group(0)
        base, _, frag = target.partition("#")
        if base == page_path:
            return f'href="#{frag}"' if frag else 'href="#main"'
        return f'href="{target}"'

    return re.sub(r'href="(#[a-z-]+)"', sub, html)


def root_absolute_assets(html):
    return re.sub(r'(src|href|poster)="(img|video|newsletters)/', r'\1="/\2/', html)


def mark_current(html, page_path):
    """aria-current on the nav/drawer link for this page."""
    if page_path == "/":
        return html
    return re.sub(
        r'(<a class="(?:site-nav__link|mobile-drawer__link)" href="%s")' % re.escape(page_path),
        r'\1 aria-current="page"',
        html,
    )


def promote_heading(section_html):
    """The first section of an interior page owns the page's <h1>."""
    section_html = re.sub(r"<h2(\s[^>]*)?>", lambda m: "<h1%s>" % (m.group(1) or ""), section_html, count=1)
    section_html = re.sub(r"</h2>", "</h1>", section_html, count=1)
    return re.sub(r'<section class="', '<section class="section--page-top ', section_html, count=1)


def featured_artists():
    """Home page strip: the first four roster cards, linking through to the full roster."""
    roster = read("sections/roster.html")
    cards = re.findall(r"\n        <article class=\"artist-card.*?\n        </article>", roster, re.S)
    head, _, _ = roster.partition('<div class="roster__grid')
    head = head.replace('class="roster roster--v4 section reveal" id="roster"',
                        'class="roster roster--v4 roster--featured section reveal" id="featured-artists"')
    head = head.replace(
        '<a class="btn-cta" href="#contact" data-en="Book an Artist" data-es="Reservar Artista">Book an Artist</a>',
        '<a class="btn-cta" href="/artists/" data-en="All Artists →" data-es="Todos los Artistas →">All Artists →</a>',
    )
    cards_html = "".join(cards[:4]).replace('href="#releases"', 'href="/artists/"')
    return (
        head
        + '<div class="roster__grid roster__grid--v4">'
        + cards_html
        + "\n      </div>\n    </div>\n  </section>\n"
    )


def build_page(page):
    path = page["path"]
    body = []
    for i, name in enumerate(page["sections"]):
        html = featured_artists() if name == "@featured" else read(f"sections/{name}.html")
        if i == 0 and path != "/":
            html = promote_heading(html)
        body.append(html.rstrip("\n"))

    head = (
        read("partials/head.html")
        .replace("{{TITLE}}", page["title"])
        .replace("{{OG_TITLE}}", page["og_title"])
        .replace("{{DESCRIPTION}}", page["description"])
        .replace("{{PATH}}", path)
    )
    chrome_top = "\n\n".join(read(f"partials/{p}.html").rstrip("\n") for p in ("ticker", "header", "drawer"))
    chrome_bottom = "\n\n".join(read(f"partials/{p}.html").rstrip("\n") for p in ("miniplayer", "actionbar", "footer"))

    if path == "/":
        legacy = {k: v for k, v in ROUTES.items() if k not in ("#top",) and not v.startswith("/#")}
        head = head.replace("</head>", LEGACY_REDIRECT % json.dumps(legacy) + "</head>", 1)

    html = (
        head.replace("<head>", "<head>\n  " + GENERATED_NOTE.strip(), 1)
        + "\n"
        + chrome_top
        + '\n\n<main id="main">\n'
        + "\n\n".join(body)
        + "\n</main>\n\n"
        + chrome_bottom
        + '\n\n<script src="/assets/site.js" defer></script>\n</body>\n</html>\n'
    )
    html = reroute(html, path)
    html = root_absolute_assets(html)
    html = mark_current(html, path)

    out = ROOT / path.strip("/") / "index.html" if path != "/" else ROOT / "index.html"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(html, encoding="utf-8")
    return out.relative_to(ROOT), len(html)


if __name__ == "__main__":
    for page in PAGES:
        out, size = build_page(page)
        print(f"  {str(out):28} {size / 1024:6.1f} KB")
